// Generated by `uptide pack new` (packages/core/src/packs/tooling/registry-file.ts).
// Every pack in this tree, with the status `uptide pack test --write` recorded for it.

import type { PackVerification, RegisteredPack } from './contract.js';
import { stripePack } from './stripe/index.js';
import stripeVerification from './stripe/verification.json' with { type: 'json' };
import { zodPack } from './zod/index.js';
import zodVerification from './zod/verification.json' with { type: 'json' };

export const REGISTRY: readonly RegisteredPack[] = [
  { dir: 'stripe', pack: stripePack, verification: stripeVerification as PackVerification },
  { dir: 'zod', pack: zodPack, verification: zodVerification as PackVerification },
];
