/**
 * `packs/registry.ts` is generated: `uptide pack new` adds an entry by rendering the whole
 * file again from the entries already there, so it is always in the one form biome accepts
 * and a hand edit never has to be merged with a generated one.
 */
export interface RegistryEntry {
  /** The pack's directory under `packs/`. */
  dir: string;
  /** The exported `Pack` constant (`zodPack`). */
  name: string;
}

const HEADER = `// Generated by \`uptide pack new\` (packages/core/src/packs/tooling/registry-file.ts).
// Every pack in this tree, with the status \`uptide pack test --write\` recorded for it.`;

export function renderRegistry(entries: readonly RegistryEntry[]): string {
  const sorted = [...entries].sort((a, b) => a.dir.localeCompare(b.dir));
  const imports = sorted.flatMap((e) => [
    `import { ${e.name} } from './${e.dir}/index.js';`,
    `import ${verificationName(e)} from './${e.dir}/verification.json' with { type: 'json' };`,
  ]);
  const rows = sorted.map(
    (e) =>
      `  { dir: '${e.dir}', pack: ${e.name}, verification: ${verificationName(e)} as PackVerification },`,
  );
  return [
    HEADER,
    "import type { PackVerification, RegisteredPack } from './contract.js';",
    ...imports,
    '',
    'export const REGISTRY: readonly RegisteredPack[] = [',
    ...rows,
    '];',
    '',
  ].join('\n');
}

function verificationName(e: RegistryEntry): string {
  return `${e.name.replace(/Pack$/, '')}Verification`;
}

/** The entries of a registry file as rendered above. */
export function parseRegistry(text: string): RegistryEntry[] {
  return [...text.matchAll(/\{ dir: '([^']+)', pack: (\w+),/g)].map((m) => ({
    dir: m[1] as string,
    name: m[2] as string,
  }));
}

/** `@ai-sdk/react` → `ai-sdk-react`: the directory of a package's pack. */
export function packDir(name: string): string {
  return name.replace(/^@/, '').replace(/[/.]/g, '-').toLowerCase();
}

/** `@ai-sdk/react` → `aiSdkReactPack`: the exported constant. */
export function packConstant(name: string): string {
  const words = packDir(name)
    .split(/[^a-z0-9]+/)
    .filter(Boolean);
  const camel = words.map((w, i) => (i === 0 ? w : `${w[0]?.toUpperCase()}${w.slice(1)}`)).join('');
  return `${/^[0-9]/.test(camel) ? `p${camel}` : camel}Pack`;
}
