export const css = `
:root{color-scheme:dark light;--bg:#0e0e11;--panel:#131316;--border:#2a2a2f;--text:#f2f1ec;--muted:#b4b3ad;--accent:#e0a458;--red:#ff8e91;--amber:#e9b55d;--gray:#c0bfc8;--green:#8dd5ae}
@media(prefers-color-scheme:light){:root{--bg:#f8f7f3;--panel:#fff;--border:#d5d3ca;--text:#202026;--muted:#5c5b56;--accent:#895113;--red:#a51e32;--amber:#815100;--gray:#595963;--green:#18663b}}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--text);font:15px/1.55 'IBM Plex Sans',system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:40px 28px 64px}h1{font-size:32px;letter-spacing:-1px;margin:12px 0 4px}h2{font-size:20px;margin:30px 0 12px}h3{font-size:16px;margin:0}.brand{font-weight:700;color:var(--accent);letter-spacing:2px}.meta,.muted{color:var(--muted)}.meta{display:flex;gap:8px 24px;flex-wrap:wrap}.summary,.package,.notes,.next{border:1px solid var(--border);border-radius:10px;background:var(--panel);margin:16px 0;overflow:hidden}.dep{display:grid;grid-template-columns:minmax(160px,1fr) 2fr;gap:8px;padding:16px 20px;border-bottom:1px solid var(--border);text-decoration:none;color:var(--text)}.dep:last-child{border-bottom:0}.dep strong{display:block}.breaking{color:var(--red)}.deprecated{color:var(--amber)}.unverified{color:var(--gray)}.safe{color:var(--green)}.package>header h2{margin:0 0 4px}.package>header{padding:18px 20px;border-bottom:1px solid var(--border)}details{border-top:1px solid var(--border)}summary{padding:14px 20px;cursor:pointer}summary:hover{background:color-mix(in srgb,var(--accent) 6%,transparent)}summary .counts{display:block;margin-left:16px;font-size:13px;color:var(--muted)}.group-note{margin:0 20px 12px}.site{padding:14px 20px;border-top:1px solid var(--border)}a{color:var(--accent);overflow-wrap:anywhere}p{overflow-wrap:anywhere;margin:8px 0}code,pre,.mono{font-family:'JetBrains Mono',ui-monospace,monospace;font-size:12px}pre{margin:12px 0 0;padding:8px 0;background:var(--bg);border:1px solid var(--border);border-radius:6px;overflow:auto;tab-size:2}.code-line{display:block;padding:0 12px;min-height:1.5em}.number{display:inline-block;width:4ch;margin-right:12px;text-align:right;color:var(--muted);user-select:none}.hit{background:color-mix(in srgb,var(--accent) 14%,var(--bg));border-left:3px solid var(--accent);padding-left:9px}.more{padding:12px 20px;color:var(--muted)}.notes ul{padding:0 40px 12px}.next{padding:4px 20px 16px}.command{display:flex;gap:12px;align-items:center;justify-content:space-between;margin:8px 0;padding:12px;border:1px solid var(--border);border-radius:6px}.command code{white-space:pre-wrap;overflow-wrap:anywhere}button,input{font:inherit;border:1px solid var(--border);border-radius:6px;color:var(--text);background:var(--panel);padding:8px 12px}button{cursor:pointer}button[aria-pressed=true]{border-color:var(--accent);color:var(--accent)}button:focus-visible,input:focus-visible,summary:focus-visible,a:focus-visible{outline:2px solid var(--accent);outline-offset:3px}.filters{display:flex;gap:8px;flex-wrap:wrap;margin:24px 0 12px}.filters input{flex:1;min-width:180px}.notice{border-left:3px solid var(--accent);padding:8px 14px;margin:16px 0}footer{margin-top:28px;color:var(--muted);font-size:13px}[hidden]{display:none!important}
.compiler{margin-top:8px;border:0}.compiler summary{padding:4px 0;font-size:12px;color:var(--muted)}.compiler pre{white-space:pre-wrap;overflow-wrap:anywhere;padding:12px}
@media(max-width:600px){main{padding:24px 14px}.dep{grid-template-columns:1fr;padding:14px}.site,summary,.package>header h2{margin:0 0 4px}.package>header{padding:12px}.command{align-items:flex-start}h1{font-size:26px}}
@media print{:root{--bg:#fff;--panel:#fff;--border:#bbb;--text:#111;--muted:#444;--accent:#644018;--red:#8a1823;--amber:#714800;--gray:#444;--green:#17582e}body{font-size:10pt}main{max-width:none;padding:0}.filters,button{display:none!important}[hidden]:not(.filters):not(button){display:block!important}details::details-content{display:block!important;content-visibility:visible!important}details>*:not(summary){display:block!important}.package,.summary,.notes{overflow:visible}pre{white-space:pre-wrap;overflow:visible}.site{break-inside:avoid}a{color:inherit;text-decoration:none}.dep{break-inside:avoid}#empty-filter{display:none!important}}
`;
export const js = `
(()=>{
const controls=document.querySelector('.filters'); controls.hidden=false;
let active='all'; const search=document.querySelector('#search');
function filter(){const q=search.value.toLowerCase(); let count=0;
 document.querySelectorAll('.package').forEach(p=>{let shown=0;const groups=p.querySelectorAll('.group');
 groups.forEach(g=>{g.hidden=!(active==='all'||g.dataset.severity===active)||!((g.dataset.rule||'')+' '+g.textContent).toLowerCase().includes(q); if(!g.hidden)shown++;});
 p.querySelectorAll('.deprecated-section').forEach(d=>{d.hidden=![...d.querySelectorAll('.group')].some(g=>!g.hidden);});
 p.hidden=groups.length?shown===0:active!=='all'||!p.textContent.toLowerCase().includes(q);
 const row=document.querySelector('[data-package="'+p.id+'"]');if(row)row.hidden=p.hidden;if(!p.hidden)count++;
 });document.querySelector('#empty-filter').hidden=count>0;
}
controls.querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{active=b.dataset.filter;controls.querySelectorAll('button').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));filter();}));search.addEventListener('input',filter);
document.querySelectorAll('[data-copy]').forEach(b=>{b.hidden=false;b.addEventListener('click',async()=>{const text=b.parentElement.querySelector('code').textContent;try{await navigator.clipboard.writeText(text);b.textContent='Copied';}catch{const range=document.createRange();range.selectNodeContents(b.parentElement.querySelector('code'));const s=getSelection();s.removeAllRanges();s.addRange(range);b.textContent='Selected — copy manually';}});});
document.querySelectorAll('.compiler a').forEach(a=>a.addEventListener('click',()=>{const target=document.querySelector(a.getAttribute('href'));for(let p=target;p;p=p.parentElement){if(p.tagName==='DETAILS')p.open=true;}}));
let opened=[];addEventListener('beforeprint',()=>{opened=[...document.querySelectorAll('details:not([open])')];opened.forEach(d=>d.open=true);});addEventListener('afterprint',()=>opened.forEach(d=>d.open=false));
})();
`;
