// The npm page shows the README and LICENSE of the package directory; ours live at the
// repository root. Copy them in for the tarball and remove them again afterwards. NOTICE
// travels with them: Apache-2.0 section 4(d) requires it in every distribution.
import { copyFileSync, existsSync, rmSync } from 'node:fs';

const files = ['README.md', 'LICENSE', 'NOTICE'];
const clean = process.argv.includes('--clean');
for (const file of files) {
  const here = new URL(`../${file}`, import.meta.url);
  if (clean) rmSync(here, { force: true });
  else copyFileSync(new URL(`../../../${file}`, import.meta.url), here);
}

// Generated by `pnpm build`, never committed: refuse to pack a tarball without the notices
// for what dist bundles rather than publish one that is silently missing them.
if (!clean && !existsSync(new URL('../THIRD-PARTY-NOTICES', import.meta.url))) {
  console.error('THIRD-PARTY-NOTICES is missing: run pnpm build before packing');
  process.exit(1);
}
